# Use a imagem oficial do Golang como base
FROM golang:1.21.0

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie todo o código fonte para o diretório de trabalho
COPY . .

# Compile a aplicação Go para o sistema operacional Linux e arquitetura AMD64
RUN go build -o migration  cmd/migration/gorm.go


# Comando para executar a aplicação quando o contêiner for iniciado
CMD ["./migration"]